### ISSUE TITLE
Alternative solution

### ISSUE THREAD

**Issue by ckcollab** [miedzinski/import-pypi#1]
Would this solution work?

```python
import pip

def install(package):
    pip.main(['install', package])

if __name__ == '__main__':
    install('argh')
```

**Comment by miedzinski** [comment]
This `install` implementation is better, but you still need an import hook (`PipFinder`). :)

**Comment by ckcollab** [comment]
What do you mean? I just mean for pip installing?

**Comment by dmtucker** [comment]
This is technically unsupported: https://github.com/pypa/pip/issues/4696

**Comment by ckcollab** [comment]
Good catch, looks like you want to use a subprocess anyway
